In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [4]:
df.tail()

     sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [5]:
df.dtypes

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [7]:
x=df.drop('variety',axis=1)
y=df['variety']

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier

log_clf=LogisticRegression()
log_dtc=DecisionTreeClassifier()
log_knc=KNeighborsClassifier()

In [ ]:
voting_clf=VotingClassifier(
    estimators=[
    ('lr',log_clf),
    ('dt',log_dtc),
    ('knn',log_knc)
],
voting='hard'
)

In [19]:
voting_clf.fit(x_train,y_train)
y_pred=voting_clf.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy is ",accuracy *100 )

confusionmatrix=confusion_matrix(y_test,y_pred)
print(confusionmatrix)

Accuracy is  100.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]