In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("PlayPredictor.csv")

In [4]:
df.head()

   Unnamed: 0   Whether Temperature Play
0           1     Sunny         Hot   No
1           2     Sunny         Hot   No
2           3  Overcast         Hot  Yes
3           4     Rainy        Mild  Yes
4           5     Rainy        Cool  Yes

In [5]:
df.dtypes

Unnamed: 0      int64
Whether        object
Temperature    object
Play           object
dtype: object

In [6]:
df.describe()

       Unnamed: 0
count   30.000000
mean    15.500000
std      8.803408
min      1.000000
25%      8.250000
50%     15.500000
75%     22.750000
max     30.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   30 non-null     int64
 1   Whether      30 non-null     object
 2   Temperature  30 non-null     object
 3   Play         30 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.1+ KB

In [8]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [9]:
df.dtypes

Whether        object
Temperature    object
Play           object
dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Play']=le.fit_transform(df['Play'])
df['Whether']=le.fit_transform(df['Whether'])
df['Temperature']=le.fit_transform(df['Temperature'])

In [11]:
df.dtypes

Whether        int64
Temperature    int64
Play           int64
dtype: object

In [12]:
df.head()

   Whether  Temperature  Play
0        2            1     0
1        2            1     0
2        0            1     1
3        1            2     1
4        1            0     1

In [13]:
print(df.columns)

Index(['Whether', 'Temperature', 'Play'], dtype='object')

In [15]:
x = df.drop("Play", axis=1)
y = df["Play"]

In [23]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

model.fit(x_train, y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import accuracy_score,classification_report
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy is : ",accuracy *100)

classification=classification_report(y_test,y_pred)
print("classification Report ",classification)

Accuracy is :  83.33333333333334
classification Report                precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.80      0.89         5

    accuracy                           0.83         6
   macro avg       0.75      0.90      0.78         6
weighted avg       0.92      0.83      0.85         6