In [23]:
import pandas as pd
import numpy as np

In [24]:
df=pd.read_csv("Advertising.csv")

In [25]:
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [26]:
df.tail()

     Unnamed: 0     TV  radio  newspaper  sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [27]:
df.dtypes

Unnamed: 0      int64
TV            float64
radio         float64
newspaper     float64
sales         float64
dtype: object

In [28]:
df.columns

Index(['Unnamed: 0', 'TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [29]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [30]:
df.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [31]:
df.isna().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [32]:
x=df.drop("sales",axis=1)
y=df["sales"]

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [34]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.metrics import mean_squared_error,r2_score
MSE=mean_squared_error(y_test,y_pred)
print("Mean Squared Error :",MSE)

R2=r2_score(y_test,y_pred)
print("R2 Value is ",R2)

Mean Squared Error : 3.174097353976105
R2 Value is  0.899438024100912