In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("HeadBrain.csv")

In [3]:
df.head()

   Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0       1          1             4512                 1530
1       1          1             3738                 1297
2       1          1             4261                 1335
3       1          1             3777                 1282
4       1          1             4177                 1590

In [4]:
df.dtypes

Gender                 int64
Age Range              int64
Head Size(cm^3)        int64
Brain Weight(grams)    int64
dtype: object

In [5]:
df.tail()

     Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

In [6]:
df.shape

(237, 4)

In [7]:
x=df[["Age Range","Head Size(cm^3)","Brain Weight(grams)"]]
y=df['Gender']

In [8]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [10]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
model=SVC()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy is :",accuracy*100)

Accuracy is : 66.66666666666666

In [12]:
from sklearn.metrics import confusion_matrix,f1_score

print(confusion_matrix(y_test, y_pred))
print("f1_score : ",f1_score(y_test, y_pred))

[[20  9]
 [ 7 12]]
f1_score :  0.7142857142857143